spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_system
    username: root
    password: basePassword09
    driverClass : com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update